import divshash as divshash# IMPORTING THE MODULE FIRST
# HELLO! I WILL FIRST SHOW A SIMPLE TUTORIAL ON HOW TO USE THE MODULE

# THIS MODULE ALLOWS TO SECURELY DECRYPT AND ENCRYPT MESSAGES

# STEP 1: ENCRYPTING:
# TO SIMPLY ENCRYPT A MESSAGE

print(divshash.HashString('Hello World!'))

# STEP 2: DECRYPTING:
# TO DECRYPT THE ENCRYPTED MESSAGE:
# WE NEED THE PRIVATE HASHKEY

print(divshash.DehashString('110110101010110.1111010100010000100100011_Y.jOOq%G.qsOX'))

